name: CI
on: [push]
jobs:
  autobrew:
    name: "Autobrew ${{ matrix.platform }} R ${{ matrix.r-version }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
          platform:
            - macos-10.13 # self-hosted
          r-version:
            - "4.2"
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: arrow
          repository: apache/arrow
          ref: b1a48c78a318402daab1d0f974825373ef41b293
          submodules: recursive

      - name: Configure autobrew script
        run: |
          # minio and sccache are pre-installed on the self-hosted 10.13 runner
          if [ ${{ matrix.platform }} != macos-10.13  ]; then
            # install minio for tests
            brew install minio
            brew install sccache
          fi
          cd arrow/r
          # Copy all *brew formulae
          cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow*.rb tools/

          # Pin the git commit in the formula to match
          cd tools
          if [ "false" == "true" ]; then
            sed -i.bak -E -e 's/apache\/arrow.git"$/apache\/arrow.git", :revision => "'"b1a48c78a318402daab1d0f974825373ef41b293"'"/' apache-arrow*.rb
          else
            sed -i.bak -E -e 's/arrow.git"$/arrow.git", :revision => "'"b1a48c78a318402daab1d0f974825373ef41b293"'"/' apache-arrow*.rb
          fi
          rm -f apache-arrow*.rb.bak

      - uses: r-lib/actions/setup-r@v2
        if: matrix.platform != 'macos-10.13'
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true
      - name: Setup R
        if: matrix.platform == 'macos-10.13'
        run: |
          # rig is a system utility that allows for switching
          # between pre-installed R version on the self-hosted runners
          rig default ${{ matrix.r-version }}
          rig system setup-user-lib
          rig system add-pak 
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: 'arrow/r'
          extra-packages: |
            any::rcmdcheck
            any::sys
            any::readr
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          NOT_CRAN: true
          ARROW_USE_PKG_CONFIG: false
          ARROW_R_DEV: true
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          SCCACHE_BUCKET: "${{ secrets.SCCACHE_BUCKET }}"
          SCCACHE_S3_KEY_PREFIX: "sccache"
  
        run: arrow/ci/scripts/r_test.sh arrow
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
